

import logic_gate as lg

if __name__ == "__main__":
    logic_gate = lg.LogicGate()

    print("AND gate")
    logic_gate.and_gate(0, 0)
    logic_gate.print_output("AND")
    logic_gate.and_gate(0, 1)
    logic_gate.print_output("AND")
    logic_gate.and_gate(1, 0)
    logic_gate.print_output("AND")
    logic_gate.and_gate(1, 1)
    logic_gate.print_output("AND")

    print()
    print("NAND gate")
    logic_gate.nand_gate(0, 0)
    logic_gate.print_output("NAND")
    logic_gate.nand_gate(0, 1)
    logic_gate.print_output("NAND")
    logic_gate.nand_gate(1, 0)
    logic_gate.print_output("NAND")
    logic_gate.nand_gate(1, 1)
    logic_gate.print_output("NAND")

    print()
    print("OR gate")
    logic_gate.or_gate(0, 0)
    logic_gate.print_output("OR")
    logic_gate.or_gate(0, 1)
    logic_gate.print_output("OR")
    logic_gate.or_gate(1, 0)
    logic_gate.print_output("OR")
    logic_gate.or_gate(1, 1)
    logic_gate.print_output("OR")

    print()
    print("NOR gate")
    logic_gate.nor_gate(0, 0)
    logic_gate.print_output("NOR")
    logic_gate.nor_gate(0, 1)
    logic_gate.print_output("NOR")
    logic_gate.nor_gate(1, 0)
    logic_gate.print_output("NOR")
    logic_gate.nor_gate(1, 1)
    logic_gate.print_output("NOR")

    print()
    print("XOR gate")
    logic_gate.xor_gate(0, 0)
    logic_gate.print_output("XOR")
    logic_gate.xor_gate(0, 1)
    logic_gate.print_output("XOR")
    logic_gate.xor_gate(1, 0)
    logic_gate.print_output("XOR")
    logic_gate.xor_gate(1, 1)
    logic_gate.print_output("XOR")
